export const BIBLE_BOOKS = [
  // 舊約 (Old Testament) - 39 卷
  { name: "創世記", chapters: 50, testament: "OT" },
  { name: "出埃及記", chapters: 40, testament: "OT" },
  { name: "利未記", chapters: 27, testament: "OT" },
  { name: "民數記", chapters: 36, testament: "OT" },
  { name: "申命記", chapters: 34, testament: "OT" },
  { name: "約書亞記", chapters: 24, testament: "OT" },
  { name: "士師記", chapters: 21, testament: "OT" },
  { name: "路得記", chapters: 4, testament: "OT" },
  { name: "撒母耳記上", chapters: 31, testament: "OT" },
  { name: "撒母耳記下", chapters: 24, testament: "OT" },
  { name: "列王紀上", chapters: 22, testament: "OT" },
  { name: "列王紀下", chapters: 25, testament: "OT" },
  { name: "歷代志上", chapters: 29, testament: "OT" },
  { name: "歷代志下", chapters: 36, testament: "OT" },
  { name: "以斯拉記", chapters: 10, testament: "OT" },
  { name: "尼希米記", chapters: 13, testament: "OT" },
  { name: "以斯帖記", chapters: 10, testament: "OT" },
  { name: "約伯記", chapters: 42, testament: "OT" },
  { name: "詩篇", chapters: 150, testament: "OT" },
  { name: "箴言", chapters: 31, testament: "OT" },
  { name: "傳道書", chapters: 12, testament: "OT" },
  { name: "雅歌", chapters: 8, testament: "OT" },
  { name: "以賽亞書", chapters: 66, testament: "OT" },
  { name: "耶利米書", chapters: 52, testament: "OT" },
  { name: "耶利米哀歌", chapters: 5, testament: "OT" },
  { name: "以西結書", chapters: 48, testament: "OT" },
  { name: "但以理書", chapters: 12, testament: "OT" },
  { name: "何西阿書", chapters: 14, testament: "OT" },
  { name: "約珥書", chapters: 3, testament: "OT" },
  { name: "阿摩司書", chapters: 9, testament: "OT" },
  { name: "俄巴底亞書", chapters: 1, testament: "OT" },
  { name: "約拿書", chapters: 4, testament: "OT" },
  { name: "彌迦書", chapters: 7, testament: "OT" },
  { name: "那鴻書", chapters: 3, testament: "OT" },
  { name: "哈巴谷書", chapters: 3, testament: "OT" },
  { name: "西番雅書", chapters: 3, testament: "OT" },
  { name: "哈該書", chapters: 2, testament: "OT" },
  { name: "撒迦利亞書", chapters: 14, testament: "OT" },
  { name: "瑪拉基書", chapters: 4, testament: "OT" },

  // 新約 (New Testament) - 27 卷
  { name: "馬太福音", chapters: 28, testament: "NT" },
  { name: "馬可福音", chapters: 16, testament: "NT" },
  { name: "路加福音", chapters: 24, testament: "NT" },
  { name: "約翰福音", chapters: 21, testament: "NT" },
  { name: "使徒行傳", chapters: 28, testament: "NT" },
  { name: "羅馬書", chapters: 16, testament: "NT" },
  { name: "哥林多前書", chapters: 16, testament: "NT" },
  { name: "哥林多後書", chapters: 13, testament: "NT" },
  { name: "加拉太書", chapters: 6, testament: "NT" },
  { name: "以弗所書", chapters: 6, testament: "NT" },
  { name: "腓立比書", chapters: 4, testament: "NT" },
  { name: "歌羅西書", chapters: 4, testament: "NT" },
  { name: "帖撒羅尼迦前書", chapters: 5, testament: "NT" },
  { name: "帖撒羅尼迦後書", chapters: 3, testament: "NT" },
  { name: "提摩太前書", chapters: 6, testament: "NT" },
  { name: "提摩太後書", chapters: 4, testament: "NT" },
  { name: "提多書", chapters: 3, testament: "NT" },
  { name: "腓利門書", chapters: 1, testament: "NT" },
  { name: "希伯來書", chapters: 13, testament: "NT" },
  { name: "雅各書", chapters: 5, testament: "NT" },
  { name: "彼得前書", chapters: 5, testament: "NT" },
  { name: "彼得後書", chapters: 3, testament: "NT" },
  { name: "約翰一書", chapters: 5, testament: "NT" },
  { name: "約翰二書", chapters: 1, testament: "NT" },
  { name: "約翰三書", chapters: 1, testament: "NT" },
  { name: "猶大書", chapters: 1, testament: "NT" },
  { name: "啟示錄", chapters: 22, testament: "NT" }
];

export const BIBLE_MAP = BIBLE_BOOKS.reduce((acc, book) => {
  acc[book.name] = book.chapters;
  return acc;
}, {});
